# Generated by Django 4.2.5 on 2023-09-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_vendor_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Vendor',
            new_name='vendor',
        ),
    ]
