# Generated by Django 4.2.5 on 2023-09-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_product_images_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
