# Generated by Django 4.2.5 on 2023-09-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_product_demo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='demo_url',
            new_name='location_url',
        ),
    ]
